apiVersion: v1
kind: Service
metadata:
   name: microservice
   labels:
      app: microservice
spec:
   type: ClusterIP
   clusterIP: 10.100.102.79
   selector:
      app: microservice
   ports:
   - name: appport
     port: 5000
     protocol: TCP
     targetPort: 5000

